name: simu_ai
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - fenics-dolfinx
  - mpich
  - pyvista
  - gmsh
  - python-gmsh
  - meshio
  - pytorch
  - cpuonly
  - matplotlib
  - numpy
  - streamlit
